name: entrance_test
description: A new Flutter project.
publish_to: 'none'
version: 18.1.20 

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  ansicolor: ^2.0.2
  cached_network_image: ^3.3.1
  dio: ^5.4.3+1
  dynamic_height_grid_view: ^0.0.4
  flutter:
    sdk: flutter

  get: ^4.6.6
  get_storage: ^2.1.1
  intl: ^0.19.0
  talker_dio_logger: ^4.2.0
  package_info_plus: ^8.0.0
  path_provider: ^2.1.3
  webview_flutter: ^4.0.0
  intl_phone_number_input: ^0.7.4
  intl_phone_field: ^3.2.0 
  image_picker: ^1.1.2
  pull_to_refresh: ^2.0.0
  sqflite: ^2.0.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
        - asset: assets/fonts/Inter-BlackItalic.ttf
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-BoldItalic.ttf
        - asset: assets/fonts/Inter-ExtraBold.ttf
        - asset: assets/fonts/Inter-ExtraBoldItalic.ttf
        - asset: assets/fonts/Inter-ExtraLight.ttf
        - asset: assets/fonts/Inter-ExtraLightItalic.ttf
        - asset: assets/fonts/Inter-Italic.ttf
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-LightItalic.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-MediumItalic.ttf
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter-SemiBoldItalic.ttf
        - asset: assets/fonts/Inter-Thin.ttf
        - asset: assets/fonts/Inter-ThinItalic.ttf  
